### ISSUE TITLE
Python serial offers a minicom-like tool

### ISSUE THREAD

**Issue by kjcole** [volkswagenfeature/mks925_Python_Lib#1]
Try this on for size:

`miniterm.py -e --filter colorize /dev/ttyS0 9600`

`Ctrl-]` exits.
`Ctrl-t Ctrl-h` brings up a help menu.

The filter makes what you type appear in red, and the response appear in white -- at least, with _my_ terminal profile...

The defaults for miniterm include no hardware handshake, and, because miniterm is actually part of the Python serial package, it may offer **LOTS** of help.

Worth noting in the documentation:

> **Miniterm supports [RFC 2217](https://tools.ietf.org/html/rfc2217.html) remote serial ports and raw sockets using URL Handlers such as rfc2217://<host>:<port> respectively socket://<host>:<port> as port argument when invoking.**

See:

- http://pyserial.readthedocs.io/en/latest/tools.html
- https://tools.ietf.org/html/rfc2217.html

**Comment by volkswagenfeature** [comment]
Thanks for the info.
